### ISSUE TITLE
Tokens deducted from M2, but not sent to M1

### ISSUE THREAD

**Issue by netdost** [movementlabsxyz/bug-tracking#11]
Multiple send transactions from M2 were done using USDC and USDT test tokens. These tokens are deducted from balances in M2 (as wallet shows the deducted values), but these tokens dont reflect in M1. Not sure where they went. The explorer is also not very easy to understand to know if transactions are stuck. If they fail, I would expect normal behaviour that tokens show in M2, but that is not the case.

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-11) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Hi, so were you trying to send USDC and USDC from your M2 address to your M1 address?

Was it some wallet service or bridge that was supposed to allow you to send USDC / USDT across the chains? 

Also, would you mind posting examples of the transactions?

Thanks!

**Comment by netdost** [comment]
Hi Andy,
   There was a Galxe Tester task open for the community program members on Discord. I was participating in the same. One of the tasks to complete using the Razor wallet were as follows:
1. Select adress on M1
2. Go to M2 and send some tokens to M1 using the address selected above.
There was no mention of a bridge or any such tool, so it was assumed the razor wallet's send function can achieve this. Looks like its not the case. If so you may close this bug.

Thanks,
- Sai






On Wednesday, May 29, 2024 at 08:15:35 AM GMT+5:30, Andy Golay ***@***.***> wrote: 







Hi, so were you trying to send USDC and USDC from your M2 address to your M1 address?

Was it some wallet service or bridge that was supposed to allow you to send USDC / USDT across the chains?

Also, would you mind posting examples of the transactions?

Thanks!
