### ISSUE TITLE
The error of get MOVE token

### ISSUE THREAD

**Issue by alphaWeGo** [movementlabsxyz/bug-tracking#12]
Is there any kind person who can help me with the answer? According to the movement documentation, I received the testnet tokens through a script, but it always reminded me that the system is busy.
<img width="831" alt="movement" src="https://github.com/movementlabsxyz/bug-tracking/assets/42131722/305878b9-31f1-4611-998d-3b42c444b5a7">

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-12) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Hi would you mind trying at https://faucet2.movementlabs.xyz and let me know if that works for you?
