### ISSUE TITLE
Movement SDK

### ISSUE THREAD

**Issue by surbhit14** [movementlabsxyz/bug-tracking#13]
How can I build on the movement SDK?
Can’t find any GitHub repo or technical documentation on it

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-13) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Hi, here's the repo:

https://github.com/movementlabsxyz/movement

Docs and Movement network testnet coming soon!
