### ISSUE TITLE
explorer APTOS don't work properly

### ISSUE THREAD

**Issue by valeria9131** [movementlabsxyz/bug-tracking#16]
![MMM](https://github.com/movementlabsxyz/bug-tracking/assets/171065423/e189fa1d-a875-4346-80d0-937405a380c9)
![MMM2](https://github.com/movementlabsxyz/bug-tracking/assets/171065423/52561ada-57d5-4de4-9b86-471a7b318cad)

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-16) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Thanks for reporting. Could you include a link to what you were looking up on the explorer?

**Comment by valeria9131** [comment]
Hi Andy! 
https://explorer.movementlabs.xyz/tx/0xc85b4482baa2c1767c037ff65360c53b74f53e0d2e31f018f3f03c7051014629
https://explorer.movementlabs.xyz/tx/0x88cde432e329d5ff0983c0e8f911575af5f88b3bf45f6ce88ece39756c06e5d9
https://explorer.movementlabs.xyz/tx/0xbedf26a54be9c79e1ac4447277a4fe873780f0c6d5d0ec4e7e190b9f69f43e4e
https://explorer.movementlabs.xyz/tx/0x393c92553a4b1150714f106eaee6fb95167c2ee57704c113245af0fbe14a10c5
https://explorer.movementlabs.xyz/tx/0x7966aadadfcf591ff2143add4b991a9c8b273606f6eb2ac63e697f4f04962585
![M1 exp 3](https://github.com/movementlabsxyz/bug-tracking/assets/171065423/6df4db69-4aa7-414b-8f91-1b5322122cc0)
the link to the explorer (highlighted) also does not work:

![explorer](https://github.com/movementlabsxyz/bug-tracking/assets/171065423/4e6622d4-ac4c-4e26-9e97-41b457dd46a2)
