### ISSUE TITLE
movement sui move build

### ISSUE THREAD

**Issue by jamesatomc** [movementlabsxyz/bug-tracking#17]
It seems that the problem is that the api sui version is too old.
<img width="939" alt="Screenshot 2024-05-31 231051" src="https://github.com/movementlabsxyz/bug-tracking/assets/56755216/9680c593-b43d-4ddd-9618-455182bb5d3d">

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-17) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Thanks for reporting, I've passed this onto the infra team and will update with any relevant progress

**Comment by jamesatomc** [comment]
If there is anything else, I will inform you again.

**Comment by andygolay** [comment]
Sounds good. Thanks, James.
