### ISSUE TITLE
Can't remove LP on M1 Devnet

### ISSUE THREAD

**Issue by lxnrdn** [movementlabsxyz/bug-tracking#21]
![image](https://github.com/movementlabsxyz/bug-tracking/assets/64420551/96ef47b7-c5bb-4a06-aac0-32f762e1f534)

![image](https://github.com/movementlabsxyz/bug-tracking/assets/64420551/c58d19a8-2881-4688-82b8-82d038bceadd)

Can't remove LP on pair : 
MOVE/BNB 
MOVE/BTC
MOVE/ETH
MOVE/SOL
MOVE/USDC
MOVE/USDT
MOVE/RAZOR

Already try to remove 25% 50% 75% Max, used gas Low / Average / High, still can't remove the LP

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-21) by [Unito](https://www.unito.io)

**Comment by 83mhpll** [comment]
hii
