### ISSUE TITLE
I can't swap in m2 devnet 

### ISSUE THREAD

**Issue by NghiavVan** [movementlabsxyz/bug-tracking#3]
After input the number of amount want to swap, it shows " Fetching best price..." even i try to refresh many times
![Screenshot 2024-05-18 201058](https://github.com/movementlabsxyz/bug-tracking/assets/104552933/9b172070-a7e5-4ea3-9664-ac18714b11eb)

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-3) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Hi, apologies for the delayed reply. Is the issue still persisting?
