### ISSUE TITLE
m2 devnet is not working for the swapping

### ISSUE THREAD

**Issue by samgit69** [movementlabsxyz/bug-tracking#4]
m2 devnet is not working for the swapping

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-4) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Hi, sorry for the delayed reply. Is this still not working for you?

**Comment by samgit69** [comment]
Nope!
![Razor-DEX-Interface](https://github.com/movementlabsxyz/bug-tracking/assets/168625475/15c9af52-2596-4340-ad90-ab2546c6af2b)
![Razor-DEX-Interface (1)](https://github.com/movementlabsxyz/bug-tracking/assets/168625475/b9d22026-8714-4bfe-89a0-394cb34b22b6)
