### ISSUE TITLE
M1 faucet 

### ISSUE THREAD

**Issue by cryptoworlldz** [movementlabsxyz/bug-tracking#5]
![wt](https://github.com/movementlabsxyz/bug-tracking/assets/101180447/b599b356-dffc-45f6-8d70-da9fec19ad09)
I haven't used faucet for a week. I tried it for the first time and=
I have 130 move in my wallet. I don't know if this could be the reason, but 46000 seconds It sucked all my potassium :D

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-5) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Hi, my apologies for the delayed reply. 

Could you try at https://faucet2.movementlabs.xyz and let me know how that works for you?
