### ISSUE TITLE
color combination for wallet 

### ISSUE THREAD

**Issue by isreal916** [movementlabsxyz/bug-tracking#6]
┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-6) by [Unito](https://www.unito.io)

**Comment by isreal916** [comment]
the color combination of the wallet is not cool for the color of the icon which make the ico not visible
kindly improve this color pallette using user experience principle

**Comment by andygolay** [comment]
Hi, which wallet are you referring to?
