### ISSUE TITLE
coonection to wallet while chosing M1 devnet

### ISSUE THREAD

**Issue by isreal916** [movementlabsxyz/bug-tracking#7]
┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-7) by [Unito](https://www.unito.io)

**Comment by isreal916** [comment]
having issue to connect while chosing the option m1 devnet in the page 
and please make sure there is a loader indicating that the wallet will popup while connecting

**Comment by andygolay** [comment]
Hi, which wallet and which page are you referring to?

**Comment by isreal916** [comment]
The razor
