### ISSUE TITLE
swapping from other coin

### ISSUE THREAD

**Issue by isreal916** [movementlabsxyz/bug-tracking#8]
having error swapping usdt back to move token which is not right it will bring some hex and address in red color and will disable the sign button which means we are having error make sure there is more optimization too

┆Issue is synchronized with this [Jira Task](https://movement.atlassian.net/browse/BUG-8) by [Unito](https://www.unito.io)

**Comment by andygolay** [comment]
Hi, which website are you referring to?

**Comment by isreal916** [comment]
The razor wallet
